// <auto-generated />
using CurrencyChange.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyChange.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328200930_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyChange.Api.Entities.ExchangeRateResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsOfUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeLastUpdateUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeLastUpdateUtc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeNextUpdateUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeNextUpdateUtc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRateResponses");
                });

            modelBuilder.Entity("CurrencyChange.Api.Entities.ExchangeRateResponse", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, decimal>", "ConversionRates", b1 =>
                        {
                            b1.Property<int>("ExchangeRateResponseId")
                                .HasColumnType("int");

                            b1.HasKey("ExchangeRateResponseId");

                            b1.ToTable("ExchangeRateResponses");

                            b1.ToJson("ConversionRates");

                            b1.WithOwner()
                                .HasForeignKey("ExchangeRateResponseId");
                        });

                    b.Navigation("ConversionRates")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
